// user register
export const USER_LOADED = 'USER_LOADED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_PROFILE_IMAGE = 'UPDATE_USER_PROFILE_IMAGE';

// add alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// accounts
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const DEBIT = 'DEBIT';
export const ADD = 'ADD';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';

// expenses
export const ADD_EXPENSES = 'ADD_EXPENSES';
export const GET_EXPENCES = 'GET_EXPENCES';

// income
export const ADD_INCOMES = 'ADD_INCOMES';
export const GET_INCOMES = 'GET_INCOMES';

// TRANFERENCES
export const ADD_TRANSFER = 'ADD_TRANSFER';
export const GET_TRANSFERENCES = 'GET_TRANSFERENCES';

// REFERENCES
export const GET_USER_REFERENCE = 'GET_USER_REFERENCE';
export const DELETE_USER_REFERENCE = 'DELETE_USER_REFERENCE';
export const GET_ACCOUNT_REFERENCE = 'GET_ACCOUNT_REFERENCE';
export const DELETE_ACCOUNT_REFERENCE = 'DELETE_ACCOUNT_REFERENCE';
export const UPDATE_REFERENCE_BY_EXPENSE = 'UPDATE_REFERENCE_BY_EXPENSE';
export const UPDATE_REFERENCE_BY_INCOME = 'UPDATE_REFERENCE_BY_INCOME';

// UI
// MODAL NOTIFICATION
export const OPEN_MODAL_NOTIFICATION = 'OPEN_MODAL_NOTIFICATION';
export const OPEN_MODAL_EDIT_PROFILE = 'OPEN_MODAL_EDIT_PROFILE';
export const MODAL_DELETE_ACCOUNT = 'MODAL_DELETE_ACCOUNT';
export const MODAL_OPEN_UPDATE_ACCOUNT = 'MODAL_OPEN_UPDATE_ACCOUNT';
export const MODAL_ADD_EXPENSE = 'MODAL_ADD_EXPENSE';
export const MODAL_ADD_INCOME = 'MODAL_ADD_INCOME';
export const MODAL_ADD_TRANFERENCE = 'MODAL_ADD_TRANFERENCE';

// UPDATE USER IMAGE PROFILE
export const OPEN_MODAL_UPDATE_USER_IMAGE = 'OPEN_MODAL_UPDATE_USER_IMAGE';

// notifications
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
